app = "unisphere"
primary_region = "sjc"

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[env]
  PORT = "3001"
  NODE_ENV = "production"
  
[mounts]
  source = "unisphere_data"
  destination = "/data" 